name: Publish
on:
  release:
    types: [published]
jobs:
  publish-on-pypi-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodule
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: make install-poetry

      - name: Install dependencies
        run: poetry install --all-extras
