name: Publish
on:
  release:
    types: [published]
jobs:
  publish-on-pypi-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodule
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: make install-poetry

      - name: Install dependencies
        run: poetry install --all-extras
