name: Python dev

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
    name: Testing Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        run: make install-poetry

      - name: Install dependencies
        run: poetry install --all-extras --with=testing

      - name: Testing
        run: poetry run make test

  linting:
    runs-on: ubuntu-latest
    name: Test Linting
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: make install-poetry

      - name: Install dependencies
        run: poetry install --all-extras --with=linting,docs

      - name: Test pre-commit checks
        run: poetry run make pre-commit-checks

      - name: Test linting
        run: poetry run make lint

      - name: Test typing
        run: poetry run make typing

      - name: Test docs
        run: poetry run make test-docs
